name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Build the app
        run: ./gradlew clean assembleDebug && tree
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app
          path: /home/runner/work/ffupdater/ffupdater/ffupdater/build/outputs/apk/debug/
        
